version: '3.8'

services:
  izinet-app:
    build:
      context: .
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    container_name: izinet-app
    restart: unless-stopped
    ports:
      # Работаем через порт 3005. 
      # Внешний трафик будет приходить сюда через Fallback от Xray (порт 443)
      - "127.0.0.1:3005:3005"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
